### ISSUE TITLE
Host demo app [SBK-325]

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ApePay#59]
Add hosting for demo app against Sepolia deployment

Make sure it works in PRs so it's easier to review changes to the component lib

related to #53

**Comment by fubuloubu** [comment]
maybe use vercel

**Comment by mikeshultz** [comment]
For RAs to easily review PR changes.

**Comment by alexisnsns** [comment]
Now that we have working local installs we can give this another try

**Comment by fubuloubu** [comment]
Note that vercel still won't work without the ability to run `ape compile`

**Comment by mikeshultz** [comment]
I mentioned it in #69, but what if we just included the manifest in the source tree?  We just commit updates when the contract changes.  It's something that we would have to explicitly do which is a little annoying, but it should be rare.  Then we don't need to compile anything during SDK builds.
