### ISSUE TITLE
Implement Claim functionality in cancel component

### ISSUE THREAD

**Issue by alexisnsns** [ApeWorX/ApePay#76]
Right now when a user cancels a deployment, he cannot claim his funds, even if there are still tokens left. 
Implement a feature on the cancelStream component which sends the money left back to the user when he cancels a stream.

cc. @fubuloubu 

<img width="340" alt="Screenshot 2023-11-16 at 16 27 35" src="https://github.com/ApeWorX/ApePay/assets/117547827/cdcac2cc-daf0-4da1-96fe-d2397109bb7c">

**Comment by fubuloubu** [comment]
related to bug here: https://github.com/ApeWorX/ApePay/blob/main/contracts/StreamManager.vy#L229
