### ISSUE TITLE
Fix WAGMI config [SBK-377]

### ISSUE THREAD

**Issue by alexisnsns** [ApeWorX/ApePay#79]
When the ApePay package is used from another repo, a WAGMI config issue arises when fetching the token balance and the native token. This makes the CreateStream component less useful than it could be as we set a default value when we cannot fetch the data.

<img width="442" alt="Screenshot 2023-11-29 at 14 38 08" src="https://github.com/ApeWorX/ApePay/assets/117547827/684e00a9-6518-47e1-9827-3680d03091a7">

**Comment by fubuloubu** [comment]
Moving away from using React
